version: '3'
services: 
   deno-app:
     build: 
       context: .
       dockerfile: Dockerfile
     ports:
       - '8000:8000'
     depends_on:
       - mongo
   mongo:
     image: mongo:latest
     container_name: mongo
     environment: 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
     env_file:
       - .env
     volumes:
       - mongo:/data/db
     ports:
       - '6000:27017'
volumes:
  mongo:
  